apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-image-scanner-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: docker-scanner.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-image-scanner
                port:
                  number: 80
