apiVersion: v1
kind: Service
metadata:
  name: docker-image-scanner
  labels:
    app: docker-image-scanner
spec:
  selector:
    app: docker-image-scanner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
